// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijvedlhfnyglwvaipicy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqdmVkbGhmbnlnbHd2YWlwaWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODI4NjYsImV4cCI6MjA3MTg1ODg2Nn0.1-uj7QLXRKhE03BV39H4MlEKLP72PbC8DCpjCVkdbd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});